#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
#include "JoystickDriver.c"
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{
	getJoystickSettings(joystick);
	if(joy1Btn(1) == 1)
	{
		motor[motorA] = 100;
	}
	else
	{
		motor[motorA] = 0;
	}

	if(joy2Btn(1) == 1)
	{
		motor[motorB] = 100;
	}
	else
	{
		motor[motorB] = 0;
	}
}
