#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

/*
   Converts the joystick value into a tetrix motor usable value

   Parameters:
   		joystickVal the value that the joystick provides (-128 to +127)

   Return value:
   		tetrix motor value (-100 to +100)
*/
int joystickToMotor(int joystickVal)
{
	// Check if joystick is in the deadzone.
	if (abs(joystickVal) < 10)
	{
		return 0;
	}
	// Gradual increase in the values of the motor.
	else if (abs(joystickVal) <= 64)
	{
		joystickVal = joystickVal - 10;
		return joystickVal*20/54;
	}
	else
	{
		return joystickVal*100/128;
	}
}

task main()
{
	while (true)
	{
		getJoystickSettings(joystick);

		motor[motorA] = joystickToMotor(joystick.joy1_y1);
		motor[motorB] = joystickToMotor(joystick.joy1_y2);

	}
}
