#pragma config(Hubs,  S1, HTMotor,  HTServo,  none,     none)
#pragma config(Motor,  mtr_S1_C1_1,     rightMotor,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotor,     tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "JoystickDriver.c"

/*
   Converts the joystick value into a tetrix motor usable value

   Parameters:
   		joystickVal the value that the joystick provides (-128 to +127)

   Return value:
   		tetrix motor value (-100 to +100 (Technically only +99))
*/
int joystickToMotor(int joystickVal)
{
	int motorValue = 0;
	// Check if joystick is in the deadzone.
	if (abs(joystickVal) <= 10){
		//Do nothing since motorValue is 0 by default.
	}
	// Gradual increase in the values of the motor.
	else if (abs(joystickVal) <= 64){
		//Fixed to account for positive or negative joystick inputs
		motorValue = ((abs(joystickVal)-10)*sgn(joystickVal))*20/54; //I would probably write a function to make this algorithm more flexible.
	}
	// Faster increase in the values of the motor.
	else if (abs(joystickVal) <= 128){
		motorValue = joystickVal*100/128;
	}
	return motorValue;
}

task main()
{
	while (true)
	{
		getJoystickSettings(joystick);
		// Make the motors move.
		motor[motorA] = joystickToMotor(joystick.joy1_y1);
		motor[motorB] = joystickToMotor(joystick.joy1_y2);

	}
}
